### ISSUE TITLE
Nice work!!! Is impossible to release the training code?

### ISSUE THREAD

**Issue by huangjch526** [rhymes-ai/Allegro#5]

**Comment by hyang0511** [comment]
Thank you for your interest in our model. 

Since our training code is heavily dependent on our specific data structure and platform, open-sourcing would be of limited value. Considering that the DiT structure of the model is consistent with Open-Sora-Plan v1.2, we highly recommend making adjustments directly to their code to ensure compatibility with our model.

If you encounter any issues during this process, feel free to discuss them in our Discord channel. We are more than happy to answer any questions related to training or testing.
